import { Inter } from "next/font/google";
import "./globals.scss";
import "bootstrap/dist/css/bootstrap.min.css";
import { Col, Container, Row } from "react-bootstrap";
import Navbar from "../app/components/Navbar";
import Aside from "./components/Aside/index.jsx";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const inter = Inter({ subsets: ["latin"] });
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <Container>
          <section>
            <Row>
              <Col md="9">
                <div className="main-section">{children}</div>
              </Col>
              <Col md="3">
                <Aside />
              </Col>
            </Row>
          </section>
        </Container>
      </body>
    </html>
  );
}
